<?php
  require 'databaseConnection/DatabaseQueries.php';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type ="text/css"href="stylesheets/allStyle.css">
    <script src="js/jquery-3.5.1.min.js"></script>
    <script src="js/testjs.js"></script>
    <title>Test</title>

</head>
<body>
  <button id = "btnMngDspt" class="mainBtn">Dispatch management</button>
    
  <div class="modal" id="divDispatchModal">
      <div class="modal-content animate" id="divIdTblComplaint" style="padding:10px;">
        <div class="clscontainer">
          <span class="refresh" title="Close Modal">&times;</span>
        </div>
        <div class=""style="overflow-x:auto;">
          <h2>DISPATCH</h2>
          <div id="complaintDetails" class="divDispatchModalStyle" style="float:left" >
            <p><b>COMPLAINT DETAILS</b></p>
            <label class="detailsLabels" >COMPLAINT NO</label><br>
            <input type="text" name="" id="cdNUM"  value="" readonly>
            <label class="detailsLabels" >NATURE OF COMPLAINT</label><br>
            <input type="text" name="" id="cdNOC"value="" readonly>
            <div id="nonAttitude">
              <label class="detailsLabels" id='dispatchCity' >CITY/MUNICIPAL</label><br>
              <input type="text" name="" id="cdLOC" value="" readonly>
              <label class="detailsLabels" id="dispatchBrgy">BARANGAY</label>
              <input type="text" name="" id="cdbrgy" value="" readonly>
            </div>
            <div id="attitude" style="display: none">
              <label class="detailsLabels" id='dispatchComplainee' >COMPLAINEE</label><br>
              <input type="text" name="" id="cdcomplainee" value="" readonly>
            </div>

          </div>

          <div id="complaintReceiver" class="divDispatchModalStyle" style="float:right;">
            <p><b>COMPLAINT RECEIVER</b></p>

            <!-- this div is autoGenerated in employeeAgent.js  -->
            <div id="divTblComplaineReceiver">
            </div>
            <!-- End autoGenerated -->

            <input type="hidden" id="empSupp" value="">
            <div id="complainthandlerBtn" style="position: relative;">
              <button type="button" id="btnSelectedEmp" class="mainBtn" disabled>Select Support</button>
              <button type="button" id="btnSet" class="mainBtn" >Manually assign receiver</button>
            </div>

            <!-- hidden Div -->
            <div id="setEmpSupp" style="display:none;padding-top:10px;">
              <div class="clscontainer">
                <span  onclick="$('#setEmpSupp').css('display','none'); $('#complainthandlerBtn').css('display','block'); $('#divTblComplaineReceiver').css('display','block')" title="Close Modal" style="position: absolute;right: 1%;top: auto;color: #000;font-size: 35px;font-weight: bold;"><a>&times;</a></span>
              </div>
              <fieldset>
                <legend><b>Assign Receiver</b></legend>
                <br>
                <input type="text" onclick="javascript:if($(this).val() !== '') {$(this).val('');} return false;" placeholder="Employee ID" list="setEmpIDList" id="setEmpID" value="">
                <datalist id="setEmpIDList">
                  <?php fillEmpSupportList(); ?>
                </datalist>
                <input type="text" placeholder="Employee Name" id="setEmpName" value="" readonly>
                <button type="button" id="btnAssignEmployeeSupport" class="mainBtn" disabled>Set Support</button>
              </fieldset>
            </div>
            <!-- End hiddenDiv -->

          </div>
        </div>
      </div>
    </div>
</body>
</html>